-- return {
--     " █████  ███████ ████████ ██████   ██████",
--     "██   ██ ██         ██    ██   ██ ██    ██",
--     "███████ ███████    ██    ██████  ██    ██",
--     "██   ██      ██    ██    ██   ██ ██    ██",
--     "██   ██ ███████    ██    ██   ██  ██████",
--     " ",
--     "    ███    ██ ██    ██ ██ ███    ███",
--     "    ████   ██ ██    ██ ██ ████  ████",
--     "    ██ ██  ██ ██    ██ ██ ██ ████ ██",
--     "    ██  ██ ██  ██  ██  ██ ██  ██  ██",
--     "    ██   ████   ████   ██ ██      ██",
-- }

-- return {
--     "                                           MMMMMMMN                       ",
--     "                                           l0MMMMMMMWO:                   ",
--     "                                              oXMMMMMMM0c                 ",
--     "                                                lNMMMMMMMMX:              ",
--     "                                                  OMMMMMMMMMx             ",
--     "                                                   oMMMMMMMMMK'           ",
--     "                                                    lMMMMMMMMMX'          ",
--     "                                                     oMMMMMMMMMX          ",
--     "    ;lll;                                             XMMMMMMMMMk         ",
--     "        :lo:                                          cMMMMMMMMMM'        ",
--     "           :oo;                                        MMMMMMMMMMd        ",
--     "              coo,                                     NMMMMMMMMMX        ",
--     "                'dd                    lldxxo,         NMMMMMMMMMW        ",
--     "                  ,kd                 kMMMMMMMk        WMMMMMMMMMW        ",
--     "                    cOc               oMMMMMMMM'      ,MMMMMMMMMMK        ",
--     "                      oO,             XMMMMMMKo       kMMMMMMMMMMo        ",
--     "                       '0l            ;xxMMMMX:      ;MMMMMMMMMMN         ",
--     "                         OXdc     '    :OMMMMMMd    'NMMMMMMMMMM:         ",
--     "                         lWMMXkdoKMW0ONMMMMMMMMM;  'XMMMMMMMMMMo          ",
--     "                           K0xoxMMMMMMMWKXMMMMMMk cNMMMMMMMMMMo           ",
--     "                           kMMKWMMMMMMMX; WMMMMMXOMMMMMMMMMMX:            ",
--     "                            :O'MMMWOMMMMMkWMMMMMMMMMMMMMMMMx              ",
--     "                              lMMMx XMMMMMMMMMMMMMMMMMMMMO,               ",
--     "                              oMX' ;kMMMMMMMMMMMMMMMMMMO;                 ",
--     "                            ,xWMOxXMMMMMMMMMMMMMMMMMKd;                   ",
--     "                  ':oolllkKXMMMMMMMMMMMMMMMMMMMMXkl'                      ",
--     "                     :okKNMMMMMMMMMMMMMMMMWXOxl,                          ",
--     "                          ';coMMMMOxddll:,                                ",
--     "                              NMkd                                        ",
--     "                           'oXMk                                          ",
--     "                        ,okWW0Oc                                          ",
-- }
return {
    "   ⣴⣶⣤⡤⠦⣤⣀⣤⠆     ⣈⣭⣿⣶⣿⣦⣼⣆          ",
    "    ⠉⠻⢿⣿⠿⣿⣿⣶⣦⠤⠄⡠⢾⣿⣿⡿⠋⠉⠉⠻⣿⣿⡛⣦       ",
    "          ⠈⢿⣿⣟⠦ ⣾⣿⣿⣷    ⠻⠿⢿⣿⣧⣄     ",
    "           ⣸⣿⣿⢧ ⢻⠻⣿⣿⣷⣄⣀⠄⠢⣀⡀⠈⠙⠿⠄    ",
    "          ⢠⣿⣿⣿⠈    ⣻⣿⣿⣿⣿⣿⣿⣿⣛⣳⣤⣀⣀   ",
    "   ⢠⣧⣶⣥⡤⢄ ⣸⣿⣿⠘  ⢀⣴⣿⣿⡿⠛⣿⣿⣧⠈⢿⠿⠟⠛⠻⠿⠄  ",
    "  ⣰⣿⣿⠛⠻⣿⣿⡦⢹⣿⣷   ⢊⣿⣿⡏  ⢸⣿⣿⡇ ⢀⣠⣄⣾⠄   ",
    " ⣠⣿⠿⠛ ⢀⣿⣿⣷⠘⢿⣿⣦⡀ ⢸⢿⣿⣿⣄ ⣸⣿⣿⡇⣪⣿⡿⠿⣿⣷⡄  ",
    " ⠙⠃   ⣼⣿⡟  ⠈⠻⣿⣿⣦⣌⡇⠻⣿⣿⣷⣿⣿⣿ ⣿⣿⡇ ⠛⠻⢷⣄ ",
    "      ⢻⣿⣿⣄   ⠈⠻⣿⣿⣿⣷⣿⣿⣿⣿⣿⡟ ⠫⢿⣿⡆     ",
    "       ⠻⣿⣿⣿⣿⣶⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⢀⣀⣤⣾⡿⠃     ",
    "        ⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠃      ",
    "         ⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠃       ",
}
